[package]
name = "async-string"
version = "0.1.0"
edition = "2024"

[target.wasm32-wasip2.dependencies] 

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls"] }
#wit-bindgen-wrpc = "0.9.0"
#wrpc-interface-http = "0.31.0"
